# DO Functions Project Configuration
# Namespace: sea-turtle-fn-namespace (NYC1)
# NOTE: Configure environment variables in DO Dashboard after deployment

packages:
  - name: enrichment
    functions:
      - name: enrich-lead
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 30000
          memory: 256
      - name: batch-enrich
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 300000
          memory: 512

  - name: data
    functions:
      - name: csv-processor
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 300000
          memory: 1024
      - name: export-csv
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 120000
          memory: 512

  - name: webhooks
    functions:
      - name: sms-inbound
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 10000
          memory: 256
      - name: voice-inbound
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 10000
          memory: 256

  - name: ai
    functions:
      - name: generate-sms
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 60000
          memory: 256

  # NEVA Agent - Perplexity-powered deep research & enrichment
  # Triggered: Pre-SMS enrichment, monthly refresh, meeting prep
  - name: neva
    functions:
      - name: enrich
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 60000
          memory: 256
      - name: research
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 120000
          memory: 512
      - name: monthly-refresh
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 60000
          memory: 256
      - name: context
        runtime: nodejs:18
        main: index.js
        web: true
        limits:
          timeout: 30000
          memory: 256
