/**
 * Cold SMS Variance Engine - Message Groups
 *
 * 7 psychological message groups (A-G) for Gianna persona
 * Each group has a specific psychological "job" it accomplishes
 *
 * @see docs/COLD_SMS_VARIANCE_ENGINE.md
 */

/**
 * Message Group Definitions
 *
 * Each group has:
 * - id: Unique identifier (A-G)
 * - name: Human-readable name
 * - psychologicalJob: What this message accomplishes psychologically
 * - triggerCondition: When to use this group
 * - maxDailyUsage: Limit per group per day
 */
export interface MessageGroup {
  id: "A" | "B" | "C" | "D" | "E" | "F" | "G";
  name: string;
  psychologicalJob: string;
  triggerCondition: string;
  maxDailyUsage: number;
  templates: ColdSMSTemplate[];
}

export interface ColdSMSTemplate {
  id: string;
  group: "A" | "B" | "C" | "D" | "E" | "F" | "G";
  text: string;
  variables: string[];
  charCount: number;
  tone: "warm" | "professional" | "casual" | "curious" | "direct";
  timeOfDay: "morning" | "afternoon" | "evening" | "any";
  dayOfWeek: "weekday" | "weekend" | "any";
}

/**
 * Group A: Neighbor/Proximity Anchor
 *
 * Psychological Job: Creates familiarity through geographic proximity.
 * Reduces stranger-danger by implying local presence.
 */
export const GROUP_A_TEMPLATES: ColdSMSTemplate[] = [
  {
    id: "A01",
    group: "A",
    text: "Hi {{firstName}}, this is Gianna from Nextier. I work with a few businesses near {{city}}. Quick question - are you still running {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 145,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A02",
    group: "A",
    text: "Hey {{firstName}}, Gianna here with Nextier. I was just in {{city}} and thought of you. Still working on {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 118,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "A03",
    group: "A",
    text: "{{firstName}}, this is Gianna from Nextier. I help businesses around {{city}}. Quick Q - is {{businessName}} still your main focus?",
    variables: ["firstName", "city", "businessName"],
    charCount: 133,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A04",
    group: "A",
    text: "Hi {{firstName}}! Gianna from Nextier here. I work with owners in the {{city}} area. Is {{businessName}} still keeping you busy?",
    variables: ["firstName", "city", "businessName"],
    charCount: 130,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "A05",
    group: "A",
    text: "{{firstName}}, Gianna with Nextier. I noticed you're based in {{city}} - I work with several businesses there. Still running {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 143,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A06",
    group: "A",
    text: "Hey {{firstName}}, it's Gianna from Nextier. I've been connecting with {{city}} business owners. Are you still at {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 133,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "A07",
    group: "A",
    text: "Hi {{firstName}}, Gianna here from Nextier. I partner with local businesses in {{city}}. Is {{businessName}} still going strong?",
    variables: ["firstName", "city", "businessName"],
    charCount: 131,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A08",
    group: "A",
    text: "{{firstName}}, this is Gianna with Nextier. I'm reaching out to {{city}} area owners. Quick check - still with {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 130,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "A09",
    group: "A",
    text: "Hey {{firstName}}, Gianna from Nextier here. Been working with businesses near you in {{city}}. Are you still operating {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 141,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "A10",
    group: "A",
    text: "Hi {{firstName}}, it's Gianna with Nextier. I specialize in helping {{city}} businesses. Quick Q - is {{businessName}} still active?",
    variables: ["firstName", "city", "businessName"],
    charCount: 137,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "A11",
    group: "A",
    text: "{{firstName}}, Gianna here from Nextier. I've been helping owners around {{city}} lately. Still running {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 123,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A12",
    group: "A",
    text: "Hey {{firstName}}! This is Gianna from Nextier. Just touched base with some {{city}} businesses. You still at {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 130,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "A13",
    group: "A",
    text: "Hi {{firstName}}, Gianna with Nextier here. I work with business owners in the {{city}} market. Still focused on {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 135,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A14",
    group: "A",
    text: "{{firstName}}, it's Gianna from Nextier. I know a few businesses in {{city}}. Wanted to check - still running {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 128,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "A15",
    group: "A",
    text: "Hey {{firstName}}, Gianna here with Nextier. I help {{city}} area business owners. Quick question - {{businessName}} still yours?",
    variables: ["firstName", "city", "businessName"],
    charCount: 132,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "A16",
    group: "A",
    text: "Hi {{firstName}}, this is Gianna from Nextier. I connect with {{city}} business owners regularly. Still with {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 131,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "A17",
    group: "A",
    text: "{{firstName}}, Gianna from Nextier. I'm based near {{city}} and work with local owners. Is {{businessName}} still going?",
    variables: ["firstName", "city", "businessName"],
    charCount: 122,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A18",
    group: "A",
    text: "Hey {{firstName}}, it's Gianna with Nextier. I support businesses throughout {{city}}. Are you still running {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 130,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "A19",
    group: "A",
    text: "Hi {{firstName}}, Gianna here from Nextier. Working with a few {{city}} owners this month. Still operating {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 129,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A20",
    group: "A",
    text: "{{firstName}}, this is Gianna with Nextier. I've been in the {{city}} area recently. Quick check - still at {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 128,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "A21",
    group: "A",
    text: "Hey {{firstName}}, Gianna from Nextier here. I partner with {{city}} business owners. Is {{businessName}} still your focus?",
    variables: ["firstName", "city", "businessName"],
    charCount: 128,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "A22",
    group: "A",
    text: "Hi {{firstName}}! Gianna with Nextier. I've helped several businesses near {{city}}. Still working on {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 124,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "A23",
    group: "A",
    text: "{{firstName}}, Gianna here from Nextier. I focus on {{city}} area businesses. Quick Q - is {{businessName}} still active?",
    variables: ["firstName", "city", "businessName"],
    charCount: 125,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "A24",
    group: "A",
    text: "Hey {{firstName}}, this is Gianna from Nextier. I work in the {{city}} market. Still running {{businessName}} these days?",
    variables: ["firstName", "city", "businessName"],
    charCount: 126,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "A25",
    group: "A",
    text: "Hi {{firstName}}, Gianna with Nextier. Just reaching out to {{city}} business owners. Are you still at {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 125,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
];

/**
 * Group B: Industry/Niche Relevance
 *
 * Psychological Job: Establishes credibility through industry expertise.
 * Shows you understand their world and speak their language.
 */
export const GROUP_B_TEMPLATES: ColdSMSTemplate[] = [
  {
    id: "B01",
    group: "B",
    text: "Hi {{firstName}}, Gianna from Nextier. I work specifically with {{industry}} businesses. Quick Q - still running {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 134,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "B02",
    group: "B",
    text: "{{firstName}}, this is Gianna with Nextier. I specialize in helping {{industry}} owners. Is {{businessName}} still your main focus?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 138,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "B03",
    group: "B",
    text: "Hey {{firstName}}, Gianna here from Nextier. I focus on the {{industry}} space. Still working on {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 118,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "B04",
    group: "B",
    text: "Hi {{firstName}}, it's Gianna from Nextier. I partner with {{industry}} business owners. Are you still at {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 129,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "B05",
    group: "B",
    text: "{{firstName}}, Gianna with Nextier. I help {{industry}} owners with growth. Quick check - still running {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 125,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "B06",
    group: "B",
    text: "Hey {{firstName}}, this is Gianna from Nextier. Been working with a lot of {{industry}} folks lately. Still at {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 134,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "B07",
    group: "B",
    text: "Hi {{firstName}}, Gianna here with Nextier. I know the {{industry}} space well. Is {{businessName}} still keeping you busy?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 127,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "B08",
    group: "B",
    text: "{{firstName}}, it's Gianna from Nextier. I've helped many {{industry}} businesses grow. Still focused on {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 128,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "B09",
    group: "B",
    text: "Hey {{firstName}}, Gianna from Nextier here. {{industry}} is my specialty. Quick question - still running {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 127,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "B10",
    group: "B",
    text: "Hi {{firstName}}, this is Gianna with Nextier. I understand {{industry}} challenges. Are you still operating {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 132,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "B11",
    group: "B",
    text: "{{firstName}}, Gianna here from Nextier. I work exclusively with {{industry}} owners. Still at {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 117,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "B12",
    group: "B",
    text: "Hey {{firstName}}! Gianna from Nextier. I've been deep in the {{industry}} world. Is {{businessName}} still going strong?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 126,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "B13",
    group: "B",
    text: "Hi {{firstName}}, Gianna with Nextier here. I connect with {{industry}} business owners. Still running {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 127,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "B14",
    group: "B",
    text: "{{firstName}}, this is Gianna from Nextier. The {{industry}} market is my focus. Quick Q - still with {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 124,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "B15",
    group: "B",
    text: "Hey {{firstName}}, it's Gianna with Nextier. I support {{industry}} owners specifically. Are you still at {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 129,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "B16",
    group: "B",
    text: "Hi {{firstName}}, Gianna from Nextier. I've worked with dozens of {{industry}} businesses. Still focused on {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 132,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "B17",
    group: "B",
    text: "{{firstName}}, Gianna here with Nextier. I'm passionate about helping {{industry}} owners. Is {{businessName}} still active?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 131,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "B18",
    group: "B",
    text: "Hey {{firstName}}, this is Gianna from Nextier. I get {{industry}} - it's what I do. Still running {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 119,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "B19",
    group: "B",
    text: "Hi {{firstName}}, Gianna with Nextier. I've seen how {{industry}} works firsthand. Are you still operating {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 130,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "B20",
    group: "B",
    text: "{{firstName}}, it's Gianna from Nextier. I love working with {{industry}} businesses. Quick check - still at {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 130,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "B21",
    group: "B",
    text: "Hey {{firstName}}, Gianna here from Nextier. {{industry}} owners are my people. Is {{businessName}} still your main thing?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 127,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "B22",
    group: "B",
    text: "Hi {{firstName}}, this is Gianna with Nextier. I focus on the {{industry}} sector. Still working on {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 123,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "B23",
    group: "B",
    text: "{{firstName}}, Gianna from Nextier. I bring value to {{industry}} business owners. Are you still running {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 128,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "B24",
    group: "B",
    text: "Hey {{firstName}}, Gianna with Nextier here. The {{industry}} space is where I thrive. Still at {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 118,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "B25",
    group: "B",
    text: "Hi {{firstName}}, it's Gianna from Nextier. I'm all about {{industry}} growth. Quick Q - is {{businessName}} still active?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 127,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
];

/**
 * Group C: Timing/Context Hook
 *
 * Psychological Job: Creates urgency through relevant timing.
 * Connects outreach to real-world events or seasons.
 */
export const GROUP_C_TEMPLATES: ColdSMSTemplate[] = [
  {
    id: "C01",
    group: "C",
    text: "Hi {{firstName}}, Gianna from Nextier. With Q1 starting, I'm connecting with business owners. Still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 128,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C02",
    group: "C",
    text: "{{firstName}}, this is Gianna with Nextier. New year, new goals - reaching out to owners like you. Is {{businessName}} still going?",
    variables: ["firstName", "businessName"],
    charCount: 137,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C03",
    group: "C",
    text: "Hey {{firstName}}, Gianna here from Nextier. End of month is always busy - quick check, still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 118,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C04",
    group: "C",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Before the quarter ends, wanted to check - still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 125,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C05",
    group: "C",
    text: "{{firstName}}, Gianna with Nextier. Spring is a big growth season - are you still focused on {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 114,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "C06",
    group: "C",
    text: "Hey {{firstName}}, this is Gianna from Nextier. Busy season approaching - quick Q, still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 122,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C07",
    group: "C",
    text: "Hi {{firstName}}, Gianna here with Nextier. Mid-week check-in - is {{businessName}} still keeping you busy?",
    variables: ["firstName", "businessName"],
    charCount: 112,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C08",
    group: "C",
    text: "{{firstName}}, it's Gianna from Nextier. Planning for next quarter - wanted to see if you're still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 125,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C09",
    group: "C",
    text: "Hey {{firstName}}, Gianna from Nextier here. Tax season wrap-up - still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 101,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C10",
    group: "C",
    text: "Hi {{firstName}}, this is Gianna with Nextier. Summer slowdown is a great time to chat - still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 122,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "C11",
    group: "C",
    text: "{{firstName}}, Gianna here from Nextier. Before the holiday rush, quick check - is {{businessName}} still active?",
    variables: ["firstName", "businessName"],
    charCount: 119,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C12",
    group: "C",
    text: "Hey {{firstName}}, Gianna with Nextier. Year-end planning time - are you still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 112,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C13",
    group: "C",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Fresh start of the week - wanted to check on {{businessName}}. Still yours?",
    variables: ["firstName", "businessName"],
    charCount: 125,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C14",
    group: "C",
    text: "{{firstName}}, this is Gianna with Nextier. Fall is prime business season - still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 113,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C15",
    group: "C",
    text: "Hey {{firstName}}, Gianna from Nextier. Budget season is here - quick Q, still focused on {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 113,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C16",
    group: "C",
    text: "Hi {{firstName}}, Gianna here with Nextier. Post-holiday catchup - are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 106,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "C17",
    group: "C",
    text: "{{firstName}}, it's Gianna from Nextier. Conference season coming up - is {{businessName}} still your main focus?",
    variables: ["firstName", "businessName"],
    charCount: 119,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C18",
    group: "C",
    text: "Hey {{firstName}}, this is Gianna with Nextier. Month-end push - wanted to check if you're still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 128,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C19",
    group: "C",
    text: "Hi {{firstName}}, Gianna from Nextier. Planning my outreach for this quarter - still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 119,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C20",
    group: "C",
    text: "{{firstName}}, Gianna here from Nextier. Back-to-business after the weekend - is {{businessName}} still going strong?",
    variables: ["firstName", "businessName"],
    charCount: 123,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C21",
    group: "C",
    text: "Hey {{firstName}}, Gianna with Nextier. Strategic planning time - are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 105,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C22",
    group: "C",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Midyear is a great checkpoint - still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 115,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "C23",
    group: "C",
    text: "{{firstName}}, this is Gianna with Nextier. Wrapping up the week - quick check, is {{businessName}} still active?",
    variables: ["firstName", "businessName"],
    charCount: 118,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "C24",
    group: "C",
    text: "Hey {{firstName}}, Gianna from Nextier here. Review season coming - wanted to see if you're still focused on {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 132,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "C25",
    group: "C",
    text: "Hi {{firstName}}, Gianna with Nextier. End of day check-in - are you still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 108,
    tone: "warm",
    timeOfDay: "evening",
    dayOfWeek: "weekday",
  },
];

/**
 * Group D: Social Proof/Referral Implication
 *
 * Psychological Job: Leverages social proof and implied referrals.
 * Creates trust through association with others.
 */
export const GROUP_D_TEMPLATES: ColdSMSTemplate[] = [
  {
    id: "D01",
    group: "D",
    text: "Hi {{firstName}}, Gianna from Nextier. Your name came up when I was chatting with {{city}} owners. Still running {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 135,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D02",
    group: "D",
    text: "{{firstName}}, this is Gianna with Nextier. A colleague mentioned you might be a good fit. Is {{businessName}} still active?",
    variables: ["firstName", "businessName"],
    charCount: 126,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "D03",
    group: "D",
    text: "Hey {{firstName}}, Gianna here from Nextier. I've helped other {{industry}} owners - wanted to check on {{businessName}}. Still yours?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 138,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "D04",
    group: "D",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Several owners in your area work with me. Are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 125,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "D05",
    group: "D",
    text: "{{firstName}}, Gianna with Nextier. Your business came up in a conversation recently. Is {{businessName}} still going strong?",
    variables: ["firstName", "businessName"],
    charCount: 128,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D06",
    group: "D",
    text: "Hey {{firstName}}, this is Gianna from Nextier. I work with similar businesses to yours. Still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 124,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "D07",
    group: "D",
    text: "Hi {{firstName}}, Gianna here with Nextier. Other {{city}} owners have found value here. Are you still focused on {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 139,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D08",
    group: "D",
    text: "{{firstName}}, it's Gianna from Nextier. I noticed you're in the same space as some clients I help. Still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 130,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "D09",
    group: "D",
    text: "Hey {{firstName}}, Gianna from Nextier here. Your peers in {{industry}} are seeing results. Is {{businessName}} still active?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 129,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D10",
    group: "D",
    text: "Hi {{firstName}}, this is Gianna with Nextier. Fellow business owners recommended I reach out. Still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 132,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "D11",
    group: "D",
    text: "{{firstName}}, Gianna here from Nextier. I've worked with businesses like {{businessName}} before. Are you still there?",
    variables: ["firstName", "businessName"],
    charCount: 122,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D12",
    group: "D",
    text: "Hey {{firstName}}, Gianna with Nextier. Your business profile caught my eye - similar to others I help. Still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 135,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "D13",
    group: "D",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Owners in your network trust me with their growth. Is {{businessName}} still going?",
    variables: ["firstName", "businessName"],
    charCount: 132,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D14",
    group: "D",
    text: "{{firstName}}, this is Gianna with Nextier. I've helped businesses in {{city}} succeed. Still running {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 123,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "D15",
    group: "D",
    text: "Hey {{firstName}}, Gianna from Nextier. Someone suggested you'd be great to connect with. Still focused on {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 129,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D16",
    group: "D",
    text: "Hi {{firstName}}, Gianna here with Nextier. Other owners in your space have benefited from chatting. Are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 140,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "D17",
    group: "D",
    text: "{{firstName}}, it's Gianna from Nextier. Your industry peers are making moves - wanted to check if you're still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 140,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "D18",
    group: "D",
    text: "Hey {{firstName}}, this is Gianna with Nextier. I partner with several {{industry}} businesses. Is {{businessName}} still active?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 132,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "D19",
    group: "D",
    text: "Hi {{firstName}}, Gianna from Nextier. A business similar to yours just had a breakthrough. Still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 130,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D20",
    group: "D",
    text: "{{firstName}}, Gianna here from Nextier. I was just talking to another owner who knows you. Are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 131,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "D21",
    group: "D",
    text: "Hey {{firstName}}, Gianna with Nextier. Fellow {{city}} business owners speak highly of you. Still running {{businessName}}?",
    variables: ["firstName", "city", "businessName"],
    charCount: 128,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "D22",
    group: "D",
    text: "Hi {{firstName}}, it's Gianna from Nextier. I work with a network of {{industry}} owners. Is {{businessName}} still your focus?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 132,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "D23",
    group: "D",
    text: "{{firstName}}, this is Gianna with Nextier. Your name keeps coming up in business circles. Still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 121,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "D24",
    group: "D",
    text: "Hey {{firstName}}, Gianna from Nextier here. I help owners who've been referred my way. Are you still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 131,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "D25",
    group: "D",
    text: "Hi {{firstName}}, Gianna with Nextier. Connected owners often share referrals - you came up. Still focused on {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 132,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
];

/**
 * Group E: Value/Benefit Curiosity
 *
 * Psychological Job: Creates curiosity about potential value.
 * Hints at benefit without being promotional.
 */
export const GROUP_E_TEMPLATES: ColdSMSTemplate[] = [
  {
    id: "E01",
    group: "E",
    text: "Hi {{firstName}}, Gianna from Nextier. I help owners save time on growth. Quick Q - still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 118,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "E02",
    group: "E",
    text: "{{firstName}}, this is Gianna with Nextier. I spotted an opportunity that might interest you. Is {{businessName}} still active?",
    variables: ["firstName", "businessName"],
    charCount: 130,
    tone: "curious",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E03",
    group: "E",
    text: "Hey {{firstName}}, Gianna here from Nextier. There might be something valuable for you here. Still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 124,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "E04",
    group: "E",
    text: "Hi {{firstName}}, it's Gianna from Nextier. I've got insights that help {{industry}} owners. Still running {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 129,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E05",
    group: "E",
    text: "{{firstName}}, Gianna with Nextier. I found something that might benefit your business. Is {{businessName}} still going?",
    variables: ["firstName", "businessName"],
    charCount: 125,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "E06",
    group: "E",
    text: "Hey {{firstName}}, this is Gianna from Nextier. I think there's an opportunity here for you. Still focused on {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 131,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "E07",
    group: "E",
    text: "Hi {{firstName}}, Gianna here with Nextier. I help owners unlock growth potential. Are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 122,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "E08",
    group: "E",
    text: "{{firstName}}, it's Gianna from Nextier. Something interesting came across my desk about your space. Still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 132,
    tone: "curious",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E09",
    group: "E",
    text: "Hey {{firstName}}, Gianna from Nextier here. I've got ideas that might help you grow. Still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 121,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "E10",
    group: "E",
    text: "Hi {{firstName}}, this is Gianna with Nextier. I see potential in what you're building. Is {{businessName}} still active?",
    variables: ["firstName", "businessName"],
    charCount: 125,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "E11",
    group: "E",
    text: "{{firstName}}, Gianna here from Nextier. I help businesses like yours streamline growth. Still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 128,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "E12",
    group: "E",
    text: "Hey {{firstName}}, Gianna with Nextier. I noticed a growth opportunity in {{industry}}. Are you still at {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 126,
    tone: "curious",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E13",
    group: "E",
    text: "Hi {{firstName}}, it's Gianna from Nextier. I have something worth sharing with you. Is {{businessName}} still yours?",
    variables: ["firstName", "businessName"],
    charCount: 120,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "E14",
    group: "E",
    text: "{{firstName}}, this is Gianna with Nextier. I specialize in finding hidden opportunities. Still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 127,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E15",
    group: "E",
    text: "Hey {{firstName}}, Gianna from Nextier. There's something here that could make a difference for you. Still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 133,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "E16",
    group: "E",
    text: "Hi {{firstName}}, Gianna here with Nextier. I help {{industry}} owners find untapped potential. Still focused on {{businessName}}?",
    variables: ["firstName", "industry", "businessName"],
    charCount: 135,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E17",
    group: "E",
    text: "{{firstName}}, it's Gianna from Nextier. I think you might be sitting on some opportunities. Is {{businessName}} still going?",
    variables: ["firstName", "businessName"],
    charCount: 130,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "E18",
    group: "E",
    text: "Hey {{firstName}}, this is Gianna with Nextier. I've got some thoughts that might interest you. Still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 126,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E19",
    group: "E",
    text: "Hi {{firstName}}, Gianna from Nextier. I see pathways to growth others might miss. Are you still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 127,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "E20",
    group: "E",
    text: "{{firstName}}, Gianna here from Nextier. Something in your profile sparked an idea. Is {{businessName}} still active?",
    variables: ["firstName", "businessName"],
    charCount: 121,
    tone: "curious",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "E21",
    group: "E",
    text: "Hey {{firstName}}, Gianna with Nextier. I've helped similar owners discover new angles. Still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 127,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "E22",
    group: "E",
    text: "Hi {{firstName}}, it's Gianna from Nextier. I spot growth levers that others overlook. Are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 126,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E23",
    group: "E",
    text: "{{firstName}}, this is Gianna with Nextier. I've got an angle that might resonate with you. Still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 128,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "E24",
    group: "E",
    text: "Hey {{firstName}}, Gianna from Nextier here. There's potential here worth exploring. Is {{businessName}} still your focus?",
    variables: ["firstName", "businessName"],
    charCount: 127,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "E25",
    group: "E",
    text: "Hi {{firstName}}, Gianna with Nextier. I help unlock what's already working in your favor. Still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 124,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
];

/**
 * Group F: Simple Check-in
 *
 * Psychological Job: Low-pressure connection.
 * Non-threatening, easy to respond to.
 */
export const GROUP_F_TEMPLATES: ColdSMSTemplate[] = [
  {
    id: "F01",
    group: "F",
    text: "Hi {{firstName}}, Gianna from Nextier. Just checking in - are you still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 97,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "F02",
    group: "F",
    text: "{{firstName}}, this is Gianna with Nextier. Quick check - is {{businessName}} still keeping you busy?",
    variables: ["firstName", "businessName"],
    charCount: 104,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "F03",
    group: "F",
    text: "Hey {{firstName}}, Gianna here from Nextier. Hope you're well - still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 93,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "F04",
    group: "F",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Wanted to see if you're still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 102,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "F05",
    group: "F",
    text: "{{firstName}}, Gianna with Nextier. Just touching base - is {{businessName}} still going?",
    variables: ["firstName", "businessName"],
    charCount: 93,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "F06",
    group: "F",
    text: "Hey {{firstName}}, this is Gianna from Nextier. Simple question - still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 95,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "F07",
    group: "F",
    text: "Hi {{firstName}}, Gianna here with Nextier. Checking in - are you still focused on {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 103,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "F08",
    group: "F",
    text: "{{firstName}}, it's Gianna from Nextier. Quick Q - is {{businessName}} still active?",
    variables: ["firstName", "businessName"],
    charCount: 88,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "F09",
    group: "F",
    text: "Hey {{firstName}}, Gianna from Nextier here. Just wanted to check - still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 101,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "F10",
    group: "F",
    text: "Hi {{firstName}}, this is Gianna with Nextier. Are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 85,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "F11",
    group: "F",
    text: "{{firstName}}, Gianna here from Nextier. Brief check-in - still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 96,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "F12",
    group: "F",
    text: "Hey {{firstName}}, Gianna with Nextier. Is {{businessName}} still yours?",
    variables: ["firstName", "businessName"],
    charCount: 73,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "F13",
    group: "F",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Hoping you're well - still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 94,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "F14",
    group: "F",
    text: "{{firstName}}, this is Gianna with Nextier. Still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 78,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "F15",
    group: "F",
    text: "Hey {{firstName}}, Gianna from Nextier. Curious - is {{businessName}} still going strong?",
    variables: ["firstName", "businessName"],
    charCount: 93,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "F16",
    group: "F",
    text: "Hi {{firstName}}, Gianna here with Nextier. Quick question - still focused on {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 99,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "F17",
    group: "F",
    text: "{{firstName}}, it's Gianna from Nextier. Just saying hi - are you still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 95,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "F18",
    group: "F",
    text: "Hey {{firstName}}, this is Gianna with Nextier. Checking - is {{businessName}} still active?",
    variables: ["firstName", "businessName"],
    charCount: 96,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "F19",
    group: "F",
    text: "Hi {{firstName}}, Gianna from Nextier. Hope all's well - still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 93,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "F20",
    group: "F",
    text: "{{firstName}}, Gianna here from Nextier. Is {{businessName}} still your main thing?",
    variables: ["firstName", "businessName"],
    charCount: 86,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "F21",
    group: "F",
    text: "Hey {{firstName}}, Gianna with Nextier. Quick check - still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 85,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "F22",
    group: "F",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Reaching out - is {{businessName}} still going?",
    variables: ["firstName", "businessName"],
    charCount: 96,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "F23",
    group: "F",
    text: "{{firstName}}, this is Gianna with Nextier. Hope you're doing great - still at {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 100,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "F24",
    group: "F",
    text: "Hey {{firstName}}, Gianna from Nextier here. Are you still operating {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 89,
    tone: "casual",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "F25",
    group: "F",
    text: "Hi {{firstName}}, Gianna with Nextier. Wanted to connect - still running {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 95,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
];

/**
 * Group G: Direct Qualifying Question
 *
 * Psychological Job: Quickly qualifies interest/fit.
 * Respects their time, gets to the point.
 */
export const GROUP_G_TEMPLATES: ColdSMSTemplate[] = [
  {
    id: "G01",
    group: "G",
    text: "Hi {{firstName}}, Gianna from Nextier. Are you looking to grow {{businessName}} this year?",
    variables: ["firstName", "businessName"],
    charCount: 93,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "G02",
    group: "G",
    text: "{{firstName}}, this is Gianna with Nextier. Is growth a priority for {{businessName}} right now?",
    variables: ["firstName", "businessName"],
    charCount: 101,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G03",
    group: "G",
    text: "Hey {{firstName}}, Gianna here from Nextier. Are you actively working on growing {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 102,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "G04",
    group: "G",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Is {{businessName}} in growth mode or maintenance mode?",
    variables: ["firstName", "businessName"],
    charCount: 102,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G05",
    group: "G",
    text: "{{firstName}}, Gianna with Nextier. Straight up - are you looking to expand {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 97,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "G06",
    group: "G",
    text: "Hey {{firstName}}, this is Gianna from Nextier. Would you say {{businessName}} is ready for the next level?",
    variables: ["firstName", "businessName"],
    charCount: 111,
    tone: "curious",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "G07",
    group: "G",
    text: "Hi {{firstName}}, Gianna here with Nextier. Is scaling {{businessName}} on your radar?",
    variables: ["firstName", "businessName"],
    charCount: 91,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "G08",
    group: "G",
    text: "{{firstName}}, it's Gianna from Nextier. Are you focused on growing {{businessName}} this quarter?",
    variables: ["firstName", "businessName"],
    charCount: 103,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G09",
    group: "G",
    text: "Hey {{firstName}}, Gianna from Nextier here. Is now a good time to talk about growing {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 106,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "G10",
    group: "G",
    text: "Hi {{firstName}}, this is Gianna with Nextier. Are you open to exploring growth for {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 105,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "G11",
    group: "G",
    text: "{{firstName}}, Gianna here from Nextier. Would growth support for {{businessName}} be welcome?",
    variables: ["firstName", "businessName"],
    charCount: 98,
    tone: "professional",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "G12",
    group: "G",
    text: "Hey {{firstName}}, Gianna with Nextier. Is {{businessName}} where you want it to be right now?",
    variables: ["firstName", "businessName"],
    charCount: 98,
    tone: "curious",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G13",
    group: "G",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Are you looking for ways to accelerate {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 105,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "G14",
    group: "G",
    text: "{{firstName}}, this is Gianna with Nextier. Is growing {{businessName}} a 2024 goal for you?",
    variables: ["firstName", "businessName"],
    charCount: 98,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G15",
    group: "G",
    text: "Hey {{firstName}}, Gianna from Nextier. Quick question - is {{businessName}} hitting its potential?",
    variables: ["firstName", "businessName"],
    charCount: 104,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "G16",
    group: "G",
    text: "Hi {{firstName}}, Gianna here with Nextier. Are you interested in taking {{businessName}} further?",
    variables: ["firstName", "businessName"],
    charCount: 102,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G17",
    group: "G",
    text: "{{firstName}}, it's Gianna from Nextier. Is expansion something {{businessName}} needs right now?",
    variables: ["firstName", "businessName"],
    charCount: 102,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "G18",
    group: "G",
    text: "Hey {{firstName}}, this is Gianna with Nextier. Would help growing {{businessName}} be useful to you?",
    variables: ["firstName", "businessName"],
    charCount: 106,
    tone: "warm",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G19",
    group: "G",
    text: "Hi {{firstName}}, Gianna from Nextier. Honest question - do you want to grow {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 99,
    tone: "direct",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "G20",
    group: "G",
    text: "{{firstName}}, Gianna here from Nextier. Is growth something you're actively pursuing for {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 110,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "any",
  },
  {
    id: "G21",
    group: "G",
    text: "Hey {{firstName}}, Gianna with Nextier. Are you ready to level up {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 87,
    tone: "casual",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
  {
    id: "G22",
    group: "G",
    text: "Hi {{firstName}}, it's Gianna from Nextier. Is now the right time to focus on growing {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 107,
    tone: "professional",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G23",
    group: "G",
    text: "{{firstName}}, this is Gianna with Nextier. Is {{businessName}} ready for its next chapter?",
    variables: ["firstName", "businessName"],
    charCount: 97,
    tone: "curious",
    timeOfDay: "morning",
    dayOfWeek: "any",
  },
  {
    id: "G24",
    group: "G",
    text: "Hey {{firstName}}, Gianna from Nextier here. Are you actively looking to scale {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 100,
    tone: "direct",
    timeOfDay: "afternoon",
    dayOfWeek: "weekday",
  },
  {
    id: "G25",
    group: "G",
    text: "Hi {{firstName}}, Gianna with Nextier. Would you like help unlocking growth for {{businessName}}?",
    variables: ["firstName", "businessName"],
    charCount: 101,
    tone: "warm",
    timeOfDay: "morning",
    dayOfWeek: "weekday",
  },
];

/**
 * All message groups combined
 */
export const MESSAGE_GROUPS: MessageGroup[] = [
  {
    id: "A",
    name: "Neighbor/Proximity Anchor",
    psychologicalJob:
      "Creates familiarity through geographic proximity. Reduces stranger-danger by implying local presence.",
    triggerCondition: "Lead has city/location data available",
    maxDailyUsage: 500,
    templates: GROUP_A_TEMPLATES,
  },
  {
    id: "B",
    name: "Industry/Niche Relevance",
    psychologicalJob:
      "Establishes credibility through industry expertise. Shows you understand their world.",
    triggerCondition: "Lead has industry/niche classification",
    maxDailyUsage: 500,
    templates: GROUP_B_TEMPLATES,
  },
  {
    id: "C",
    name: "Timing/Context Hook",
    psychologicalJob:
      "Creates relevance through timing. Connects outreach to real-world events or seasons.",
    triggerCondition: "Default fallback when other data unavailable",
    maxDailyUsage: 400,
    templates: GROUP_C_TEMPLATES,
  },
  {
    id: "D",
    name: "Social Proof/Referral Implication",
    psychologicalJob:
      "Leverages social proof and implied referrals. Creates trust through association.",
    triggerCondition: "Lead in area/industry with existing client success",
    maxDailyUsage: 300,
    templates: GROUP_D_TEMPLATES,
  },
  {
    id: "E",
    name: "Value/Benefit Curiosity",
    psychologicalJob:
      "Creates curiosity about potential value. Hints at benefit without being promotional.",
    triggerCondition: "Lead profile suggests growth-oriented owner",
    maxDailyUsage: 400,
    templates: GROUP_E_TEMPLATES,
  },
  {
    id: "F",
    name: "Simple Check-in",
    psychologicalJob:
      "Low-pressure connection. Non-threatening, easy to respond to.",
    triggerCondition: "Re-engagement after previous non-response",
    maxDailyUsage: 600,
    templates: GROUP_F_TEMPLATES,
  },
  {
    id: "G",
    name: "Direct Qualifying Question",
    psychologicalJob:
      "Quickly qualifies interest/fit. Respects their time, gets to the point.",
    triggerCondition: "High-value lead with strong qualification signals",
    maxDailyUsage: 300,
    templates: GROUP_G_TEMPLATES,
  },
];

/**
 * Get all templates flattened
 */
export function getAllTemplates(): ColdSMSTemplate[] {
  return MESSAGE_GROUPS.flatMap((group) => group.templates);
}

/**
 * Get templates by group ID
 */
export function getTemplatesByGroup(
  groupId: "A" | "B" | "C" | "D" | "E" | "F" | "G",
): ColdSMSTemplate[] {
  const group = MESSAGE_GROUPS.find((g) => g.id === groupId);
  return group?.templates || [];
}

/**
 * Get group by ID
 */
export function getGroupById(
  groupId: "A" | "B" | "C" | "D" | "E" | "F" | "G",
): MessageGroup | undefined {
  return MESSAGE_GROUPS.find((g) => g.id === groupId);
}

/**
 * Count total templates
 */
export function getTotalTemplateCount(): number {
  return MESSAGE_GROUPS.reduce((sum, group) => sum + group.templates.length, 0);
}
