export enum ResponseClassification {
  POSITIVE = "POSITIVE",
  NEUTRAL = "NEUTRAL",
  WRONG_NUMBER = "WRONG_NUMBER",
  PROFANITY = "PROFANITY",
  DNC_REQUEST = "DNC_REQUEST",
  UNCLASSIFIED = "UNCLASSIFIED",
}

export enum InboxPriority {
  HOT = "HOT",
  WARM = "WARM",
  COLD = "COLD",
  URGENT = "URGENT",
}

export enum BucketType {
  UNIVERSAL_INBOX = "UNIVERSAL_INBOX",
  POSITIVE_RESPONSES = "POSITIVE_RESPONSES",
  NEUTRAL_REVIEW = "NEUTRAL_REVIEW",
  WRONG_NUMBER = "WRONG_NUMBER",
  PROFANITY_REVIEW = "PROFANITY_REVIEW",
  BLACKLIST = "BLACKLIST",
  LEGAL_DNC = "LEGAL_DNC",
  FOLLOW_UP = "FOLLOW_UP",
}

export enum SuppressionType {
  BLACKLIST = "BLACKLIST",
  LEGAL_DNC = "LEGAL_DNC",
  WRONG_NUMBER = "WRONG_NUMBER",
}

export enum AchievementType {
  NUMBER_CONFIRMED = "NUMBER_CONFIRMED",
  POSITIVE_RESPONSE = "POSITIVE_RESPONSE",
  LEAD_CONVERTED = "LEAD_CONVERTED",
  CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED",
  MESSAGES_PROCESSED = "MESSAGES_PROCESSED",
  BLACKLIST_REVIEWED = "BLACKLIST_REVIEWED",
  STREAK_MILESTONE = "STREAK_MILESTONE",
  STREAK_3_DAY = "STREAK_3_DAY",
  STREAK_7_DAY = "STREAK_7_DAY",
  STREAK_30_DAY = "STREAK_30_DAY",
  LEVEL_UP = "LEVEL_UP",
  DAILY_GOAL = "DAILY_GOAL",
  FIRST_CONTACT = "FIRST_CONTACT",
  SPEED_DEMON = "SPEED_DEMON",
  INBOX_ZERO = "INBOX_ZERO",
  TOP_PERFORMER = "TOP_PERFORMER",
  AI_ASSIST_MASTER = "AI_ASSIST_MASTER",
  BLACKLIST_GUARDIAN = "BLACKLIST_GUARDIAN",
  QUALITY_CHECKER = "QUALITY_CHECKER",
}

export enum BadgeTier {
  BRONZE = "BRONZE",
  SILVER = "SILVER",
  GOLD = "GOLD",
  PLATINUM = "PLATINUM",
  DIAMOND = "DIAMOND",
}

export enum InitialMessageCategory {
  INTRODUCTION = "INTRODUCTION",
  FOLLOW_UP = "FOLLOW_UP",
  RE_ENGAGEMENT = "RE_ENGAGEMENT",
  PROPERTY_SPECIFIC = "PROPERTY_SPECIFIC",
  MARKET_UPDATE = "MARKET_UPDATE",
  SEASONAL = "SEASONAL",
  EVENT_BASED = "EVENT_BASED",
}

export enum MessageTone {
  PROFESSIONAL = "PROFESSIONAL",
  FRIENDLY = "FRIENDLY",
  CASUAL = "CASUAL",
  URGENT = "URGENT",
  EMPATHETIC = "EMPATHETIC",
}
